export const GET_TRANSLATED_TEXT = 'GET_TRANSLATED_TEXT';
export const SET_TEXT_TO_BE_TRANSLATED = 'SET_TEXT_TO_BE_TRANSLATED';
export const SET_HISTORY = 'SET_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
